### PR TITLE
[183] Show when an upcoming game is going to be released

### LINKED ISSUE #194: Sorting doesn't work with masonry view
**Describe the bug**
Sorting stopped(?) working for masonry view

**Additional context**
This may or may not have something to do with the new sorting function recently added. Will have to look what's going on.

### PR DESCRIPTION
**Pull request by paddykontschak**
## About
Making a wishlist is great to show the games you're interested in. But maybe the games aren't even out yet. Users will now be able to see a number of remaining days left until the release of the games. This number appears on the game card next to the existing content.

## Additional features
- text-based views show a proper text, cover based views only a number
- users can hide release days per list altogether
- users can hide game info displayed on masonry covers
- masonry lists can be sorted correctly (fixes #194)

## Screenshots
Screenshot 2020-02-11 at 9 24 48 PM
Screenshot 2020-02-11 at 9 24 16 PM
Screenshot 2020-02-11 at 9 24 53 PM
Screenshot 2020-02-11 at 8 54 43 PM
Screenshot 2020-02-11 at 8 55 00 PM
Screenshot 2020-02-11 at 9 01 52 PM
Screenshot 2020-02-11 at 9 02 09 PM

### CODE REVIEW

File: src/components/GameCards/GameCard.js [hunk 1]
```diff
@@ -35,6 +39,40 @@ export default {
...
+
+      if (daysUntilRelease > 0) {
+        return daysUntilRelease;
+      } else if (daysUntilRelease === 0) {
+        return 'Today';
+      } else if (daysUntilRelease < 0) {
+        return '';
+      }
+
+      return 'TBA';
```
Comment (romancm) [inline src/components/GameCards/GameCard.js]: consider using ternaries instead:

```
if (daysUntilRelease >= 0) {
  return daysUntilRelease === 0 ? 'Today' : daysUntilRelease;
}

return daysUntilRelease < 0 ? '' : 'TBA';
```

File: src/components/GameCards/GameCard.js [hunk 2]
```diff
@@ -35,6 +39,40 @@ export default {
...
+    },
+
+    releaseDateText() {
+      if (this.releaseDate > 1) {
+        return `Releases in ${this.releaseDate} days`;
+      } else if (this.releaseDate === 1) {
+        return 'Releases tomorrow';
+      } else if (this.releaseDate === 'Today' && new Date().getHours() < 15) {
```
Comment (romancm) [inline src/components/GameCards/GameCard.js]: `new Date().getHours() < 15` what is this for?

Comment (paddykontschak) [reply src/components/GameCards/GameCard.js]: It's an arbitrary check if it's 3pm. I'm just gonna assume that the game has been released by 3pm. This way it won't show "releases today" all day long, but "released today" at some point.

File: src/components/GameCards/GameCard.js [hunk 3]
```diff
@@ -35,6 +40,47 @@ export default {
...
 
+    releaseDate() {
+      const releaseDate = this.game
+        && this.game.release_dates
+        && this.game.release_dates.filter(
+          ({ platform }) => this.platform.id === platform,
+        )
+        && this.game.release_dates.filter(
+          ({ platform }) => this.platform.id === platform,
+        )[0].date;
```
Comment (romancm) [inline src/components/GameCards/GameCard.js]: you can use `find` instead of `filter` to get the first instance, then you don't have to get it using `[0]`
